### ISSUE TITLE
HU17 - Menú de opciones

### ISSUE THREAD

**Issue by elle184** [elle184/vinilapp#10]
| Nombre | Menú de opciones | 
| -------- | ------------------------------ |
Descripción | Como usuario visitante, quiero ver el menú de opciones de la aplicación para poder acceder a las funcionalidades disponibles y seleccionar las que me interesen. |
Criterios de aceptación | <ol><li>La pantalla del menú debe cargar correctamente al iniciar la aplicación.</li><li>El menú debe incluir opciones para acceder a la información de los coleccionistas y a la información de interés para los usuarios visitantes.</li></ol> |
Mockup | <img width="1137" alt="Screenshot 2024-04-07 at 8 26 47 AM" src="https://github.com/elle184/vinilapp/assets/129342513/3cd09bb4-27a7-402d-baf4-137e22160a5e">|
Responsable | Juan David Ardila |
Puntos de historia | 5 |

**Comment by jdardila12** [comment]
**Tareas**

*Menú de opciones:*
- Diseñar la pantalla del menú de opciones.
- Desarrollar la lógica para cargar correctamente las opciones del menú al iniciar la aplicación.
- Implementar las funcionalidades para acceder a la información de los coleccionistas y a la información de interés para los usuarios visitantes.

*Formulario de creación:*
- Desarrollar un formulario para ingresar los detalles de un nuevo álbum.

*Envío de datos al backend:*
- Configurar la comunicación para enviar los datos del formulario al backend.

*Pruebas:*
- Realizar pruebas básicas para asegurar el correcto funcionamiento del formulario y la comunicación con el backend.

*Integración:*
- Fusionar los cambios en la rama principal una vez completada la implementación y las pruebas.
